import Intro from "@/components/Layout/Intro";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Container from "./../container/Container";
import SubHeader from "./../components/Layout/subHeader";
import Footer from "@/components/Layout/Footer";
import Products from "@/components/Layout/Products";
import axios from "axios";

export default function Home({ product }) {


  return (
    <>
      <Head>
        <title>Nikeshop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <section className="pt-20">
          <Intro />
          <div className="max-w-7xl mx-auto">
            <SubHeader />
            <Products product={product}/>
          </div>
          <Footer />
        </section>
      </Container>
    </>
  );
}

export async function getStaticProps(context) {
  const { data } = await axios.get("http://localhost:3000/api/product");

  console.log(data);

  return {
    props: {
      product: data,
    },
  };
}
